### ISSUE TITLE
Call for Speakers – February 2018

### ISSUE THREAD

**Issue by felixjung** [berlinjs/berlinjs.org#243]
# How to submit a talk to BerlinJS?
You can either comment on this issue or send us an email at (insert email address – we need an address everyone has access to)

### When and where will it be?
- February 15th
- Adalbertstraße 8, 10999 Berlin, Germany

### What should I talk about?
Anything JavaScript (JavaScript / JavaScript community related), that gets you excited.

### Do I need to be an expert to talk?
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

### How long should my talk be?
Between five and twentyfive minutes. There won’t be any formal Q&A.

### What should be in my talk submission?
Your name, Twitter handle / email address, talk title and a few sentences describing what you want to talk about would be great.

### What's the A/V situation?
We'll have a projector (Full HD / HDMI) and a mic for you to use. Adapters are available.

**Comment by carolstran** [comment]
I'd love to talk to the BerlinJS community about docs! Here is my info, let me know if you have any questions 😺 

Basically, it's an extension of the lightning talk I gave at [React Day Berlin](https://www.youtube.com/watch?v=jY2xglypPkQ) because people were like 'Ok cool Carolyn use case driven docs sound nice... but how do I actually implement this?' So I wanted to add more content and rework it so that it focuses more on how it fits in a workflow, etc. 

Carolyn Stransky
@carolstran - Twitter, GitHub, everywhere
Humanizing Your Documentation 
It’s no secret that people don’t usually read technical documentation for pleasure. Users often come to your docs when they are frustrated, disappointed and at their lowest. In this talk, we’ll discuss how the language we use affects our users, the first steps towards writing use case-driven docs, and how to implement this in your developer workflow.
Runtime: 20-25 minutes

**Comment by krzkaczor** [comment]
Krzysztof Kaczor
@krzkaczor - Twitter/Github/medium
*Wonders of Typescript type system*
Lately, we observe the rise of typed additions to Javascript language like Typescript or Flow. They all seamlessly blend with Javascript while providing additional type safety. This interop with existing ecosystem forced language designers to explore ideas like gradual and structural typing. In my talk, I want to present extraordinary features of Typescript type system while building something practical — React, Redux web app. 
Runtime: 25-30 min

**Comment by sjsyrek** [comment]
Steven Syrek
@sjsyrek on Twitter, GitHub, Medium, and most other places
_Make a Lambda Calculus: Functional Programming in JavaScript... without JavaScript_
Functional programming concepts have the reputation of being hard to learn. If we start from first principles, however, they don't have to be. In this talk, I'll demonstrate how we can implement the entire universe of FP from scratch, using only JavaScript arrow functions.
I have done this as a 2 hour workshop, but I happy to condense it into a 20-30 minute "taster" for this meetup.

**Comment by veu** [comment]
Rebecca König ([@I_like_too_much](https://twitter.com/I_like_too_much))
The Little Things – An introduction to JS code golfing

Code golfing – a wonderful world of tiny unreadable programs that do a lot more than you’d think by their size. Let’s have a look at the [JS1k competition](https://js1k.com/2018-coins/), [Tetris](https://github.com/veu/mini-tetris) in 512 bytes, and how to join if you are interested. Most importantly though let’s have some fun with JavaScript without all the requirements, dependencies, and concerns we have when creating “production-ready” code.

**Comment by rmehner** [comment]
👋 

@veu @carolstran Since we've talked about your talks before, I'm very glad to see you here :) I'd love to have you on February :) We'll add you to the website ASAP

@veu how long do you think your talk would be?

@krzkaczor @sjsyrek would March work for you as well? February is pretty full and we also have #242 waiting for a couple of months already and we want to keep it at 3 talks per night, as it tends to run too long if we have even more talks :)

**Comment by krzkaczor** [comment]
@rmehner Hey, it's fine for me!

**Comment by veu** [comment]
@rmehner It will be 20-25 minutes.

**Comment by Mohamed3on** [comment]
@rmehner I'd like to submit a talk for the march one too. Should I do it here or wait for the March Call for Speakers?

**Comment by rmehner** [comment]
@Mohamed3on https://github.com/berlinjs/berlinjs.org/issues/244 :)

**Comment by rmehner** [comment]
@krzkaczor Can you still do February? Sorry for the confusion :) If so, I'd love to put you on the website.

**Comment by krzkaczor** [comment]
@rmehner yes, sure! It's actually very lucky because I just realized that I will be out of town for March.

**Comment by rmehner** [comment]
@krzkaczor just put you on the website, welcome! Please aim for the 20 minute mark, as three talks in one evening is a lot to take in for the attendees :)

**Comment by sjsyrek** [comment]
@rmehner I think that ought to be feasible. Do I need to post another issue comment for March?

**Comment by rmehner** [comment]
@sjsyrek I'll do that by hand :)
