### ISSUE TITLE
Call for Speakers – March 2018

### ISSUE THREAD

**Issue by rmehner** [berlinjs/berlinjs.org#244]
# How to submit a talk to BerlinJS?
You can either comment on this issue or send us an email at (insert email address – we need an address everyone has access to)

### When and where will it be?
- March 15th
- Adalbertstraße 8, 10999 Berlin, Germany

### What should I talk about?
Anything JavaScript (JavaScript / JavaScript community related), that gets you excited.

### Do I need to be an expert to talk?
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

### How long should my talk be?
Between five and twentyfive minutes. There won’t be any formal Q&A.

### What should be in my talk submission?
Your name, Twitter handle / email address, talk title and a few sentences describing what you want to talk about would be great.

### What's the A/V situation?
We'll have a projector (Full HD / HDMI) and a mic for you to use. Adapters are available.

**Comment by Mohamed3on** [comment]
### Name:
Mohamed Oun
### Twitter/Gmail/GitHub/anywhere: 
Mohamed3on
## Talk title:
Async Therefore Await

## Abstract:
If you've developed in JavaScript before, chances are you've come across (or wrote) a piece of spaghetti code commonly referred to as 'callback hell', which results from chaining multiple asynchronous functions together.

Async/Await is one of the most important features introduced in ES2017, which promises to solve that problem and provide a way to write clean, readable asynchronous code sans the callback hell.

Learn what async/await is, why you should consider using it, how it differs from Promises and how you can use it today!

**Comment by rmehner** [comment]
Steven Syrek
@sjsyrek on Twitter, GitHub, Medium, and most other places
Make a Lambda Calculus: Functional Programming in JavaScript... without JavaScript
Functional programming concepts have the reputation of being hard to learn. If we start from first principles, however, they don't have to be. In this talk, I'll demonstrate how we can implement the entire universe of FP from scratch, using only JavaScript arrow functions.
I have done this as a 2 hour workshop, but I happy to condense it into a 20-30 minute "taster" for this meetup.

**Comment by cristianoliveira** [comment]
###  Name:
Cristian Oliveira

### Social Network:
github: cristianoliveira
twitter: cristian_or_
facebook: cristianoliveiradarosa

### Talk title:
When React meets TDD. 🤝 

### Abstract:
This talk is about TDD and unit testing in general around the world of React. I will talk about some of the problems that we had in the past for testing UI and how we can address them using React + Enzyme and TDD.

keywords:
- UI testing
- React
- Enzyme
- Snapshots
- Testable code design
- TDD and React
- Live code examples (probably)

**Comment by radojesrb** [comment]
## Name
**Develoger**

## Online presence
Twitter: [https://twitter.com/develoger](https://twitter.com/develoger)
Blog: [https://develoger.com](https://develoger.com)
Email: dusan.radojevic@smava.de

## Talk title
Web Workers - outsource your JavaScript

## Presentation
[Google drive presentation](https://docs.google.com/presentation/d/13BffowRelyvn783nYUs8LsAAVCk-EiDOOtwEGYNZDqw/edit?usp=sharing) * please request the access I will grant it quickly.

## Highlights
If you are curious why Workers are both revolution and solution to the not needed problem this talk is for you. We are going to cover Why, When and How to approach web workers. In the age of client rich JavaScript apps, blocking stack execution queue can and will make your e-commerce solution loose potential conversions, instead of earning you the money.

## Note
I prepared this presentation for the internal company FE event. Presenting slides lasted 10 - 15 minutes and code examples lasted another 10 minutes. Which brings us to approximate 20 - 25 minutes in total.

**Comment by stefanjudis** [comment]
## Name

Stefan Judis

## Online presence

stefanjudis.com
https://twitter.com/stefanjudis
https://github.com/stefanjudis/

## Talk title

I didn't know that!

## Abstract

In 2017 I discovered ~50  things in WebDev that were unknown to me. These are now documented on my blog. The fun thing is that these are sometimes very advanced but sometimes also very basic. 

I want to share a lot of nitty-gritty details of JavaScript but also want to take away the fear of the audience to say "I don't know that" and show the power of starting a routine that helps to gain and remember knowledge.

## Note

I'll focus on the JS part and not talk about other things. :)

**Comment by metapraveen** [comment]
#### Name:
Praveen Kumar

`Twitter`: https://twitter.com/_praveen612
`Gmail`: pdnsjce
`GitHub`: https://github.com/praveen612

#### Talk title:
migrating to webpack 4

#### Abstract:
Recently upgraded an application at work from webpack 3 to 4.
Want to share some metrics and things I have learned while doing this.
I think its around 10 to 15 min talk with some code samples to show.

**Comment by sjsyrek** [comment]
I never received confirmation that I would be speaking next week, so I can't be ready in time... looking at the current schedule, my talk isn't listed anyway. I could move it to April, unless it's not something you're interested in at this time.

**Comment by felixjung** [comment]
Hey Steven. We sent you a message on Twitter last Friday, to which we haven't received a response, yet. Unfortunately we failed to check this issue for further comments from you. We're sorry. Like you said the thing got a bit too short notice, which is why we opted for another speaker, thinking you were not responding. April sounds fine to us, if you are still up for it. Again, sorry for missing your comment here.

**Comment by felixjung** [comment]
@everyone I'm closing the issue now, as we have three talks for this month's meetup. There'll be a new one for April, but it already looks like we have three talks for that edition, too (Stefan, Steven, and a mysterious third speaker). @praveen612, we'll keep your talk on the "waiting list" though. It's also possible that for whatever reason one of the speakers for April won't make it.
