### ISSUE TITLE
Talk proposal: Property-Based Testing

### ISSUE THREAD

**Issue by goblindegook** [berlinjs/berlinjs.org#260]
##### Talk title

Property-Based Testing with JSVerify

##### Abstract

Writing tests can be tricky. How do you ensure appropriate coverage yet keep things straightforward and maintainable? Generative testing exists to reinforce your tests with hundreds of randomised checks, but it requires changing your test design mentality. This talk introduces JSVerify and its underpinnings, and will help you think less about expected results and more about general behaviour that you can test.

###### Your name

Luis Rodrigues

###### Means to get in touch with you

* [Web](https://goblindegook.com)
* [Twitter](https://twitter.com/goblindegook)
* [Github](https://github.com/goblindegook)
* [Email](mailto:hello@${WEBSITE_DOMAIN})

**Comment by carolstran** [comment]
Hey @goblindegook, thanks for submitting! Sorry that it's taken this long to get back to you. 

Your talk idea is great and very relevant. The thing is, we already have a very similar topic in the backlog. Do you have any other topics that you'd like to speak about? Otherwise, if you'd still like to present on this topic, we can do that - but it would have to later in the year after we have the other one.

Let me know what you think 😊

**Comment by carolstran** [comment]
👋 @goblindegook, just checking in on this to see if you're still interested in speaking. If you don't reply within a week or so then I'll close the issue (mostly to keep everything organized) - but of course, you can always open a new one 😁

**Comment by carolstran** [comment]
👋 Closing this now, but feel free to reopen or open a new issue if you're interested in speaking in the future!
